### ISSUE TITLE
npm warning, bcoz of node version requirement

### ISSUE THREAD

**Issue by andriytyurnikov** [daaku/nodejs-freeport#7]
```
npm WARN engine freeport@1.0.3: wanted: {"node":"0.6.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
```
package may less strict version requirement to avoid warning message for those, with newer node

**Comment by andriytyurnikov** [comment]
It appears that it is fixed already, and version bump release is all that is needed.

**Comment by daaku** [comment]
Pushed `1.0.4` with the fix.
